spring :
    datasource:
            url: jdbc:mysql://localhost:3306/company
            username: root
            password:
    application:
        name: api-users
    jpa:
        hibernate:
            ddl-auto: update
server: 
    port : 9020
    error:
        include-message: always

